{"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/isRefreshTokenDeleted","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"symbolKind":"property","title":"isRefreshTokenDeleted","role":"symbol","externalID":"s:5Auth019AuthenticationErrorV21isRefreshTokenDeletedSbvp","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isRefreshTokenDeleted","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"roleHeading":"Instance Property","modules":[{"name":"Auth0"}]},"variants":[{"paths":["\/documentation\/auth0\/authenticationerror\/isrefreshtokendeleted"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"When the credentials renewal fails because the user was deleted.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isRefreshTokenDeleted"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/isRefreshTokenDeleted":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isRefreshTokenDeleted","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","title":"isRefreshTokenDeleted","type":"topic","abstract":[{"type":"text","text":"When the credentials renewal fails because the user was deleted."}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/isRefreshTokenDeleted","url":"\/documentation\/auth0\/authenticationerror\/isrefreshtokendeleted","role":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0":{"kind":"symbol","title":"Auth0","type":"topic","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","url":"\/documentation\/auth0","role":"collection"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError":{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError","role":"symbol","type":"topic","url":"\/documentation\/auth0\/authenticationerror","navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents an error during a request to the Auth0 Authentication API."}],"kind":"symbol","title":"AuthenticationError","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationError"}]}}}