{"kind":"article","hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/auth0\/authenticationerror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion"],"title":"Instance Properties","anchor":"Instance-Properties"}],"metadata":{"modules":[{"name":"Auth0"}],"roleHeading":"API Collection","title":"LocalizedError Implementations","role":"collectionGroup"},"references":{"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/helpAnchor":{"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/auth0\/authenticationerror\/helpanchor","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"helpAnchor"},"doc://com.auth0.Auth0/documentation/Auth0":{"type":"topic","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","title":"Auth0","abstract":[{"text":"SDK for Apple platforms.","type":"text"}],"role":"collection","url":"\/documentation\/auth0","kind":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/failureReason":{"abstract":[],"url":"\/documentation\/auth0\/authenticationerror\/failurereason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","title":"failureReason","role":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError":{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError","title":"AuthenticationError","url":"\/documentation\/auth0\/authenticationerror","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationError","kind":"identifier"}],"navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Represents an error during a request to the Auth0 Authentication API."}]},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/recoverySuggestion":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","url":"\/documentation\/auth0\/authenticationerror\/recoverysuggestion","title":"recoverySuggestion","type":"topic","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion"}}}