{"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion"],"generated":true,"title":"Instance Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/auth0\/authenticationerror\/localizederror-implementations"]}],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError"]]},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"LocalizedError Implementations","modules":[{"name":"Auth0"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/LocalizedError-Implementations"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.auth0.Auth0/documentation/Auth0":{"kind":"symbol","title":"Auth0","type":"topic","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","url":"\/documentation\/auth0","role":"collection"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/failureReason":{"role":"symbol","abstract":[],"type":"topic","title":"failureReason","kind":"symbol","url":"\/documentation\/auth0\/authenticationerror\/failurereason","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/recoverySuggestion":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion","url":"\/documentation\/auth0\/authenticationerror\/recoverysuggestion","title":"recoverySuggestion","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[],"role":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError":{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError","role":"symbol","type":"topic","url":"\/documentation\/auth0\/authenticationerror","navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents an error during a request to the Auth0 Authentication API."}],"kind":"symbol","title":"AuthenticationError","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationError"}]},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/helpAnchor":{"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","title":"helpAnchor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/auth0\/authenticationerror\/helpanchor","type":"topic","abstract":[],"kind":"symbol","role":"symbol"}}}