{"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion"]}],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError"]]},"metadata":{"title":"LocalizedError Implementations","roleHeading":"API Collection","modules":[{"name":"Auth0"}],"role":"collectionGroup"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/auth0\/authenticationerror\/localizederror-implementations"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/LocalizedError-Implementations"},"references":{"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/failureReason":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/auth0\/authenticationerror\/failurereason","role":"symbol","type":"topic","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason","title":"failureReason"},"doc://com.auth0.Auth0/documentation/Auth0":{"role":"collection","url":"\/documentation\/auth0","kind":"symbol","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"type":"topic","title":"Auth0","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/recoverySuggestion":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion","url":"\/documentation\/auth0\/authenticationerror\/recoverysuggestion","abstract":[],"title":"recoverySuggestion","role":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError":{"role":"symbol","url":"\/documentation\/auth0\/authenticationerror","kind":"symbol","title":"AuthenticationError","type":"topic","navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationError","kind":"identifier"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError","abstract":[{"text":"Represents an error during a request to the Auth0 Authentication API.","type":"text"}]},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/helpAnchor":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","url":"\/documentation\/auth0\/authenticationerror\/helpanchor","kind":"symbol","abstract":[],"title":"helpAnchor"}}}