{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError"]]},"metadata":{"role":"collectionGroup","title":"LocalizedError Implementations","roleHeading":"API Collection","modules":[{"name":"Auth0"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/auth0\/authenticationerror\/localizederror-implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/LocalizedError-Implementations"},"topicSections":[{"identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion"],"generated":true,"title":"Instance Properties"}],"kind":"article","references":{"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/recoverySuggestion":{"abstract":[],"url":"\/documentation\/auth0\/authenticationerror\/recoverysuggestion","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/recoverySuggestion","title":"recoverySuggestion"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/failureReason":{"kind":"symbol","type":"topic","title":"failureReason","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"failureReason","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/failureReason","url":"\/documentation\/auth0\/authenticationerror\/failurereason","role":"symbol"},"doc://com.auth0.Auth0/documentation/Auth0":{"role":"collection","type":"topic","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"kind":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","url":"\/documentation\/auth0","title":"Auth0"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError":{"abstract":[{"text":"Represents an error during a request to the Auth0 Authentication API.","type":"text"}],"title":"AuthenticationError","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"AuthenticationError","kind":"identifier"}],"navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError","url":"\/documentation\/auth0\/authenticationerror"},"doc://com.auth0.Auth0/documentation/Auth0/AuthenticationError/helpAnchor":{"abstract":[],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/AuthenticationError\/helpAnchor","title":"helpAnchor","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","url":"\/documentation\/auth0\/authenticationerror\/helpanchor"}}}