{"metadata":{"modules":[{"name":"Auth0"}],"roleHeading":"API Collection","title":"Auth0Error Implementations","role":"collectionGroup"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription"],"generated":true}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/auth0\/credentialsmanagererror\/auth0error-implementations"]}],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/Auth0Error-Implementations"},"references":{"doc://com.auth0.Auth0/documentation/Auth0":{"url":"\/documentation\/auth0","type":"topic","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","title":"Auth0","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"kind":"symbol","role":"collection"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/localizedDescription":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localizedDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription","type":"topic","kind":"symbol","url":"\/documentation\/auth0\/credentialsmanagererror\/localizeddescription","abstract":[{"type":"text","text":"Description of the error."}],"role":"symbol","title":"localizedDescription"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/errorDescription":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Description of the error."}],"title":"errorDescription","kind":"symbol","url":"\/documentation\/auth0\/credentialsmanagererror\/errordescription","type":"topic","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CredentialsManagerError"}],"kind":"symbol","role":"symbol","title":"CredentialsManagerError","abstract":[{"text":"Represents an error during a Credentials Manager operation.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CredentialsManagerError"}],"url":"\/documentation\/auth0\/credentialsmanagererror","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"}}}