{"hierarchy":{"paths":[["doc:\/\/com.auth0.Auth0\/documentation\/Auth0","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/Auth0Error-Implementations"},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/auth0\/credentialsmanagererror\/auth0error-implementations"]}],"metadata":{"modules":[{"name":"Auth0"}],"role":"collectionGroup","title":"Auth0Error Implementations","roleHeading":"API Collection"},"sections":[],"references":{"doc://com.auth0.Auth0/documentation/Auth0":{"type":"topic","abstract":[{"type":"text","text":"SDK for Apple platforms."}],"url":"\/documentation\/auth0","role":"collection","identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0","kind":"symbol","title":"Auth0"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/errorDescription":{"type":"topic","abstract":[{"type":"text","text":"Description of the error."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/errorDescription","role":"symbol","url":"\/documentation\/auth0\/credentialsmanagererror\/errordescription","kind":"symbol","title":"errorDescription"},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError/localizedDescription":{"url":"\/documentation\/auth0\/credentialsmanagererror\/localizeddescription","kind":"symbol","type":"topic","role":"symbol","title":"localizedDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError\/localizedDescription","abstract":[{"type":"text","text":"Description of the error."}]},"doc://com.auth0.Auth0/documentation/Auth0/CredentialsManagerError":{"url":"\/documentation\/auth0\/credentialsmanagererror","kind":"symbol","type":"topic","role":"symbol","title":"CredentialsManagerError","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CredentialsManagerError","kind":"identifier"}],"navigatorTitle":[{"text":"CredentialsManagerError","kind":"identifier"}],"identifier":"doc:\/\/com.auth0.Auth0\/documentation\/Auth0\/CredentialsManagerError","abstract":[{"type":"text","text":"Represents an error during a Credentials Manager operation."}]}}}